In [1]:
import pandas as pd
import glob
import numpy as np

In [2]:
import pandas as pd
import glob
path = r'data' # use your path
all_files = glob.glob(path + "/*_tracks.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True)

In [3]:
frame

recordingId  trackId  frame  trackLifetime    xCenter   yCenter  \
0                   0        0      0              0  131.38519 -34.78380   
1                   0        0      1              1  131.33830 -35.13993   
2                   0        0      2              2  131.28821 -35.50286   
3                   0        0      3              3  131.23861 -35.86783   
4                   0        0      4              4  131.18973 -36.23341   
...               ...      ...    ...            ...        ...       ...   
14175179           32      466  25286            216   18.27403  -5.41860   
14175180           32      466  25287            217   17.87039  -5.12769   
14175181           32      466  25288            218   17.46547  -4.83655   
14175182           32      466  25289            219   17.05943  -4.54523   
14175183           32      466  25290            220   16.65228  -4.25391   

            heading    width   length  xVelocity  yVelocity  xAcceleration  \
0         261.84968  1.76028  4.03141   -1.20819   -9.06651       -0.01047   
1         261.95002  1.76028  4.03141   -1.20844   -9.06017       -0.01211   
2         262.00456  1.76028  4.03141   -1.20806   -9.05198       -0.01427   
3         262.03306  1.76028  4.03141   -1.20726   -9.04039       -0.01754   
4         262.06697  1.76028  4.03141   -1.20636   -9.02442       -0.02230   
...             ...      ...      ...        ...        ...            ...   
14175179  143.47428  0.00000  0.00000  -10.06592    7.24792       -0.80318   
14175180  143.50798  0.00000  0.00000  -10.09826    7.25714       -0.80333   
14175181  143.54158  0.00000  0.00000  -10.13047    7.26611       -0.80336   
14175182  143.57504  0.00000  0.00000  -10.16261    7.27488       -0.80336   
14175183  143.60837  0.00000  0.00000  -10.19474    7.28360       -0.80336   

          yAcceleration  lonVelocity  latVelocity  lonAcceleration  \
0               0.52307      9.14622     -0.08938         -0.51631   
1               0.55970      9.14012     -0.07223         -0.55249   
2               0.61071      9.13202     -0.06276         -0.60279   
3               0.67524      9.12046     -0.05740         -0.66630   
4               0.75172      9.10455     -0.05069         -0.74145   
...                 ...          ...          ...              ...   
14175179        0.21726     12.40272     -0.16672          0.77473   
14175180        0.21772     12.43430     -0.17124          0.77531   
14175181        0.21787     12.46563     -0.17588          0.77560   
14175182        0.21789     12.49679     -0.18062          0.77579   
14175183        0.21789     12.52793     -0.18540          0.77596   

          latAcceleration  
0                 0.08452  
1                 0.09037  
2                 0.09908  
3                 0.11096  
4                 0.12583  
...                   ...  
14175179         -0.30346  
14175180         -0.30271  
14175181         -0.30216  
14175182         -0.30169  
14175183         -0.30123  

[14175184 rows x 17 columns]

In [4]:
df = frame
df

recordingId  trackId  frame  trackLifetime    xCenter   yCenter  \
0                   0        0      0              0  131.38519 -34.78380   
1                   0        0      1              1  131.33830 -35.13993   
2                   0        0      2              2  131.28821 -35.50286   
3                   0        0      3              3  131.23861 -35.86783   
4                   0        0      4              4  131.18973 -36.23341   
...               ...      ...    ...            ...        ...       ...   
14175179           32      466  25286            216   18.27403  -5.41860   
14175180           32      466  25287            217   17.87039  -5.12769   
14175181           32      466  25288            218   17.46547  -4.83655   
14175182           32      466  25289            219   17.05943  -4.54523   
14175183           32      466  25290            220   16.65228  -4.25391   

            heading    width   length  xVelocity  yVelocity  xAcceleration  \
0         261.84968  1.76028  4.03141   -1.20819   -9.06651       -0.01047   
1         261.95002  1.76028  4.03141   -1.20844   -9.06017       -0.01211   
2         262.00456  1.76028  4.03141   -1.20806   -9.05198       -0.01427   
3         262.03306  1.76028  4.03141   -1.20726   -9.04039       -0.01754   
4         262.06697  1.76028  4.03141   -1.20636   -9.02442       -0.02230   
...             ...      ...      ...        ...        ...            ...   
14175179  143.47428  0.00000  0.00000  -10.06592    7.24792       -0.80318   
14175180  143.50798  0.00000  0.00000  -10.09826    7.25714       -0.80333   
14175181  143.54158  0.00000  0.00000  -10.13047    7.26611       -0.80336   
14175182  143.57504  0.00000  0.00000  -10.16261    7.27488       -0.80336   
14175183  143.60837  0.00000  0.00000  -10.19474    7.28360       -0.80336   

          yAcceleration  lonVelocity  latVelocity  lonAcceleration  \
0               0.52307      9.14622     -0.08938         -0.51631   
1               0.55970      9.14012     -0.07223         -0.55249   
2               0.61071      9.13202     -0.06276         -0.60279   
3               0.67524      9.12046     -0.05740         -0.66630   
4               0.75172      9.10455     -0.05069         -0.74145   
...                 ...          ...          ...              ...   
14175179        0.21726     12.40272     -0.16672          0.77473   
14175180        0.21772     12.43430     -0.17124          0.77531   
14175181        0.21787     12.46563     -0.17588          0.77560   
14175182        0.21789     12.49679     -0.18062          0.77579   
14175183        0.21789     12.52793     -0.18540          0.77596   

          latAcceleration  
0                 0.08452  
1                 0.09037  
2                 0.09908  
3                 0.11096  
4                 0.12583  
...                   ...  
14175179         -0.30346  
14175180         -0.30271  
14175181         -0.30216  
14175182         -0.30169  
14175183         -0.30123  

[14175184 rows x 17 columns]

#### Number of unique trackID

In [5]:
len(df['trackId'].value_counts())

613

In [6]:
np.min(df['trackId']), np.max(df['trackId'])

(0, 612)

In [7]:
grouped_df = df.groupby('trackId')

# dv 1

In [8]:
dv1_list = list(grouped_df.std()['xVelocity'])
dv1_list

[4.443491024010919,
 1.061868845014104,
 1.2544021696945817,
 0.5251400811175494,
 0.5822756144222169,
 0.3138819025835127,
 0.47465291044499797,
 0.5869717005215656,
 0.8218575097547862,
 0.7929885046234186,
 0.9384800831506782,
 0.8850237848572554,
 0.9512346341706182,
 0.9996871280658546,
 1.1009735131263136,
 1.0577491694528114,
 1.0940501717413895,
 1.0855302662447066,
 1.0760685669995618,
 1.0806486899134242,
 1.163717032539098,
 1.2207260964567512,
 1.218839887343275,
 1.5577417121211907,
 1.7201272490307389,
 1.4082257821034692,
 1.568212684402366,
 1.7073726546672514,
 1.7396753943210306,
 2.0721532094335497,
 2.206675250640261,
 3.999301945656178,
 3.0810431262798423,
 4.897574135170127,
 5.561561214432094,
 4.278992082997858,
 7.360038827818605,
 4.962785238056241,
 5.70431520854547,
 5.662320117707638,
 5.314308493945212,
 5.618010112900867,
 4.9422866808349735,
 3.014566021136802,
 5.894143211986866,
 5.222088354224373,
 4.839432193069827,
 4.478514290498669,
 4.4014704578

# dv 2

In [9]:
dv2_list = list(grouped_df.std()['lonAcceleration'])
dv2_list

[0.72682239947147,
 0.17399623402982298,
 0.22423590760892848,
 0.06612281845089862,
 0.0641997338111234,
 0.022004020712252232,
 0.05090634525984801,
 0.07943409548634574,
 0.06720779499290207,
 0.05413558004216297,
 0.0782701045990428,
 0.10060726160256549,
 0.14860801817513186,
 0.10673451666129989,
 0.09906670139438975,
 0.13415953089016155,
 0.07433075420735905,
 0.08395590654135726,
 0.11186962205767609,
 0.09465064204268783,
 0.14223591584054732,
 0.13539029827051982,
 0.12243668854851275,
 0.1604030473716144,
 0.1679464780907062,
 0.15023834469299635,
 0.20357379672248774,
 0.2041958096946655,
 0.18786085095810068,
 0.16616189150771746,
 0.30661211463411253,
 0.39687654261017086,
 0.29052175372101396,
 0.5045383095536886,
 0.5538794655731372,
 0.5480920354935632,
 0.7736891679137263,
 0.601660841746243,
 0.49577826373712897,
 0.7411535602052741,
 0.5955768451634483,
 0.6558784481018295,
 0.5357680872184317,
 0.3727960482308189,
 0.7292646193090714,
 0.704553474999911,
 0.653984

# dv 3

In [10]:
stds_list = np.array(dv1_list)
means_list = np.array(grouped_df.mean()['xVelocity'])

In [11]:
dv3_list = (100 * stds_list) / means_list
dv3_list

array([-6.37347121e+02, -2.73435416e+03, -3.08788718e+03, -3.55875952e+03,
       -3.95824171e+03,  2.23298241e+04,  3.72185596e+04,  1.59197203e+04,
        6.80224270e+05, -8.46201430e+03, -6.01111140e+03,  5.50641051e+04,
       -3.57402186e+03,  1.46561509e+03,  9.74731881e+03,  3.10453439e+03,
       -6.50954277e+03, -1.01544869e+05, -1.93216637e+03, -3.54003202e+03,
       -3.03719349e+03, -2.62274173e+03, -1.94186621e+04,  2.10955496e+03,
        2.14679063e+03,  1.19849129e+03, -2.82060516e+03,  1.95158989e+03,
       -1.71884117e+03,  9.63769615e+03, -1.21766279e+03,  3.96161045e+03,
       -4.76997206e+03,  4.11161288e+03,  4.43980622e+02,  8.26984991e+02,
        9.76511908e+02,  5.42389934e+02, -2.91769410e+03, -1.11076700e+03,
       -4.10726506e+02,  1.48872763e+04,  6.03775041e+03,  1.39236988e+03,
       -1.66715326e+03, -1.65164492e+04,  1.14945798e+03,  3.95014933e+02,
        4.23432878e+02, -8.38106562e+04,  1.96710599e+04, -5.56342628e+02,
        5.04823381e+02,  

# dv4

In [12]:
stds_list2 = np.array(dv2_list)
means_list2 = np.array(grouped_df.mean()['lonAcceleration'])

In [13]:
dv4_list = (100 * stds_list2) / means_list2
dv4_list

array([ 4.29609629e+02,  1.25496676e+03,  1.30683751e+03,  2.65706626e+03,
        3.48059513e+03,  1.25315663e+04,  1.08627322e+04,  5.30811522e+03,
        3.50118565e+03,  2.38016714e+04,  1.06672453e+04, -7.35078748e+04,
       -2.82665990e+04, -6.23322432e+03,  1.15030739e+04,  1.89958312e+04,
        1.23177605e+04,  3.05264987e+04,  4.35078671e+03,  2.76950195e+03,
        5.60879345e+03,  8.28874256e+03,  3.53465036e+03,  1.10941752e+04,
        7.98228956e+03,  2.02129104e+04,  1.26463466e+04,  5.35963646e+03,
        5.39147672e+03,  6.77648107e+03,  4.77553938e+03,  8.24327809e+03,
        4.67021497e+03,  1.07775927e+03,  1.61602557e+03, -1.64872505e+04,
        1.33977313e+03,  7.32505700e+03,  3.28102146e+03,  1.29589031e+03,
        7.14880205e+03,  2.70250551e+03,  1.57154311e+03,  2.69939414e+03,
        3.19155105e+03,  1.93155195e+03,  4.05461444e+03,  9.68093532e+03,
        8.91341830e+03,  1.86773423e+03,  3.04417709e+03, -5.84353420e+04,
        1.53750682e+03,  

# dv 5

In [14]:
grouped_by_deacc = df[df['lonAcceleration'] < 0].groupby('trackId')

In [15]:
stds_deacc = np.array(grouped_by_deacc.std()['lonAcceleration'])

In [16]:
means_deacc = np.array(grouped_by_deacc.mean()['lonAcceleration'])

In [17]:
dv5_list = (100 * stds_deacc) / means_deacc
dv5_list

array([-156.79730179, -206.95238545, -194.06715922, -144.90933845,
       -168.94367821, -100.15980161, -203.44571799, -167.21874685,
       -116.90436355, -180.22891969, -155.88852938, -152.23247677,
       -146.48044209, -167.20606707, -223.35434508, -113.37282486,
       -160.21426809, -131.40108432, -140.10129103, -131.91637746,
       -157.69516232, -159.66287543, -140.7794365 , -211.19402053,
       -136.21214154, -120.34890685, -133.44392605, -136.38033895,
        -98.82639208, -125.78068421, -117.17934943, -180.02645269,
       -153.91328229, -173.11664695, -146.43872047, -151.84387507,
       -112.47822898, -155.98950708, -153.20726493, -150.6793795 ,
       -171.37797579, -137.84305382, -161.96499868, -183.45908164,
       -136.06593752, -167.71760549, -147.01421903, -158.7397538 ,
       -181.09216713, -143.87259629, -139.51693932, -127.0803013 ,
       -161.03442446, -146.91483319, -137.05694913, -148.23535992,
       -122.42557288, -149.1611753 , -150.93748255, -166.06164

# DV6

In [18]:
dv6_list = list(grouped_df.mad()['xVelocity'])
dv6_list

[3.032236295266183,
 0.30744293540749906,
 0.3476514109100375,
 0.06755753739250552,
 0.05797852730930609,
 0.015982455729144345,
 0.028859873053026352,
 0.046032033162515806,
 0.06285851564231161,
 0.07572432291971117,
 0.1020393780394708,
 0.08224689045222135,
 0.13105418382572234,
 0.17556989513244933,
 0.12029070725725761,
 0.142600394913407,
 0.12630362232324058,
 0.11448685998974896,
 0.17517044427397482,
 0.13848005005394295,
 0.1809017385982063,
 0.19045117213431603,
 0.16590317826857717,
 0.3353502438913762,
 0.38094983801676535,
 0.34000009948297105,
 0.354953479203653,
 0.41217005762468,
 0.42077806238333937,
 0.48183895734764254,
 0.7665297745827301,
 1.9244342066343885,
 1.1944854610296907,
 2.7966663075680107,
 4.133201627640818,
 2.7696760605276265,
 6.335185547538526,
 3.2121955297702858,
 3.816284864090767,
 3.7970129842610083,
 3.7090457318224606,
 3.930387562089947,
 3.0661806803753335,
 1.2115581800673683,
 3.8905063853942212,
 3.4152867893972885,
 2.964663991782293

# DV 7

In [19]:
dv7_list = list(grouped_df.mad()['lonAcceleration'])
dv7_list

[0.4887482044514624,
 0.04280316186305459,
 0.059105441543131354,
 0.008460284011981319,
 0.007235642505906037,
 0.001351602444816151,
 0.0030678784479794357,
 0.0072716082341417665,
 0.006289053986453718,
 0.003890031766611732,
 0.007005083977209582,
 0.008135872078887853,
 0.014303044092708961,
 0.010911750100236999,
 0.007642198997363977,
 0.01274606223212075,
 0.006566527793644958,
 0.007556757297281729,
 0.01407175309992677,
 0.012242908606530989,
 0.018936191689243653,
 0.01569919976081628,
 0.017560655685268454,
 0.023030170710110945,
 0.027479493415012837,
 0.022569418287388423,
 0.036952086950190845,
 0.03882486061936082,
 0.03623812493736936,
 0.0353544289510069,
 0.08584741419077063,
 0.16989601382463676,
 0.09327687639928996,
 0.2769049116307446,
 0.3255017749792736,
 0.28853501148827226,
 0.519628868152333,
 0.33913378578340525,
 0.2859499047619298,
 0.4513853911363369,
 0.3245135048277508,
 0.398974568304203,
 0.29614433486224273,
 0.11994584881022465,
 0.4424790763549594

# DV 8

In [20]:
percentile_25 = []
percentile_75 = []

for i in range(len(grouped_df)):
    percentile_25.append(np.percentile(grouped_df.get_group(i)['xVelocity'], 25))
    percentile_75.append(np.percentile(grouped_df.get_group(i)['xVelocity'], 75))

In [21]:
percentile_25 = np.array(percentile_25)
percentile_25

array([-2.1048150e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -3.7080000e-02,
        0.0000000e+00, -1.0003450e+00, -1.4274125e+00, -1.1007350e+00,
       -5.5368400e+00, -9.7908500e-01, -1.3239100e+00, -1.5743425e+00,
       -3.5814300e+00, -2.5627800e+00, -1.6073425e+00,  0.0000000e+00,
       -1.4892000e+00, -1.2041000e+00, -1.1149600e+00, -6.8631750e-01,
       -1.0610300e+00, -1.0545800e+00, -2.0113000e-01, -4.4074800e+00,
       -7.7368000e-01, -1.1605950e+00, -8.0045000e-01,  0.0000000e+00,
      

In [22]:
percentile_75 = np.array(percentile_75)
percentile_75

array([ 1.0413775e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.6927500e-02,
        0.0000000e+00,  1.3868350e+00,  3.8853900e+00,  1.4182975e+00,
        7.0371200e+00,  2.6321525e+00,  2.8797900e+00,  1.0884575e+00,
        1.1705600e+00,  2.1229600e+00,  1.3452475e+00,  0.0000000e+00,
        1.3734850e+00,  1.3904600e+00,  1.6537200e+00,  1.7909100e+00,
        1.3509500e+00,  1.2571900e+00,  7.9796750e-01,  1.3448200e+00,
        2.7016825e+00,  2.1057600e+00,  1.2845300e+00,  1.0808000e-01,
      

In [23]:
dv8_list = 100 * ((percentile_75 - percentile_25) / (percentile_75 + percentile_25))
dv8_list

<ipython-input-23-ec4b06e0e25c>:1: RuntimeWarning: invalid value encountered in true_divide
  dv8_list = 100 * ((percentile_75 - percentile_25) / (percentile_75 + percentile_25))


array([-2.95851190e+02,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan, -2.67994045e+02,
                   nan,  6.17656343e+02,  2.16145286e+02,  7.93239913e+02,
        8.38107553e+02,  2.18456748e+02,  2.70181505e+02, -5.48030913e+02,
       -1.97106854e+02, -1.06537675e+03, -1.12653427e+03,             nan,
       -2.47391004e+03,  1.39223009e+03,  5.13898582e+02,  2.24266189e+02,
        8.31946744e+02,  1.14099502e+03,  1.67398580e+02, -1.87820391e+02,
        1.80257157e+02,  

# dv 9

In [24]:
percentile_25_dlong = []
percentile_75_dlong = []

for i in range(len(grouped_df)):
    percentile_25_dlong.append(np.percentile(grouped_df.get_group(i)['lonAcceleration'], 25))
    percentile_75_dlong.append(np.percentile(grouped_df.get_group(i)['lonAcceleration'], 75))

In [25]:
percentile_25_dlong = np.array(percentile_25_dlong)
percentile_75_dlong = np.array(percentile_75_dlong)

In [26]:
dv9_list = 100 * ((percentile_75_dlong - percentile_25_dlong) / (percentile_75_dlong + percentile_25_dlong))
dv9_list

<ipython-input-26-de9b934ef2f4>:1: RuntimeWarning: invalid value encountered in true_divide
  dv9_list = 100 * ((percentile_75_dlong - percentile_25_dlong) / (percentile_75_dlong + percentile_25_dlong))


array([ 1.26633094e+02,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,  1.45071507e+03,
                   nan,  4.70540142e+02,  3.50051629e+02,  2.78970653e+03,
        4.23290554e+02,  9.11187036e+02,  5.14344934e+02,  3.03626656e+02,
        4.03221361e+02,  2.80408490e+02,  3.87218809e+02,             nan,
        4.56558953e+02,  4.26996967e+02,  4.03635933e+02,  8.55265700e+02,
        1.98900662e+03,  9.23597233e+02,  6.03313439e+02,  4.10259797e+02,
        4.21181271e+02,  

# dv 10

In [27]:
percentile_25_deacc = []
percentile_75_deacc = []

for i in range(len(grouped_df)):
    percentile_25_deacc.append(np.percentile(grouped_by_deacc.get_group(i)['lonAcceleration'], 25))
    percentile_75_deacc.append(np.percentile(grouped_by_deacc.get_group(i)['lonAcceleration'], 75))

In [28]:
percentile_25_deacc = np.array(percentile_25_deacc)
percentile_75_deacc = np.array(percentile_75_deacc)

In [29]:
dv10_list = 100 * ((percentile_75_deacc - percentile_25_deacc) / (percentile_75_deacc + percentile_25_deacc))
dv10_list

array([-89.41707804, -72.44174265, -73.7440906 , -74.308771  ,
       -84.15284833, -63.59004053, -83.27864583, -79.12777153,
       -78.1066732 , -68.42720148, -74.36479052, -87.83715987,
       -82.88119344, -80.44629875, -71.95192586, -80.64492985,
       -71.9544585 , -75.55018813, -84.54050388, -81.88751392,
       -82.8113029 , -86.576007  , -79.58058522, -67.39132783,
       -81.94475967, -82.41771288, -88.64672634, -78.877513  ,
       -72.20251414, -76.19282173, -82.16009356, -89.01331486,
       -73.96144014, -78.4590439 , -84.89151176, -83.05198201,
       -77.5704598 , -82.43847589, -77.95721831, -85.47795979,
       -79.42222417, -86.57657203, -80.85287516, -83.23925684,
       -82.78103564, -77.06503934, -87.71432831, -81.07058706,
       -82.40291827, -79.02851003, -84.46305075, -82.94230612,
       -79.95534192, -85.42019163, -77.92518794, -79.44293504,
       -84.79392199, -86.42837976, -83.20764087, -80.93755854,
       -73.42471652, -82.81595888, -84.2989418 , -76.60

# dv 11

In [30]:
# std list for xVelocity
stds_list 

array([4.44349102, 1.06186885, 1.25440217, 0.52514008, 0.58227561,
       0.3138819 , 0.47465291, 0.5869717 , 0.82185751, 0.7929885 ,
       0.93848008, 0.88502378, 0.95123463, 0.99968713, 1.10097351,
       1.05774917, 1.09405017, 1.08553027, 1.07606857, 1.08064869,
       1.16371703, 1.2207261 , 1.21883989, 1.55774171, 1.72012725,
       1.40822578, 1.56821268, 1.70737265, 1.73967539, 2.07215321,
       2.20667525, 3.99930195, 3.08104313, 4.89757414, 5.56156121,
       4.27899208, 7.36003883, 4.96278524, 5.70431521, 5.66232012,
       5.31430849, 5.61801011, 4.94228668, 3.01456602, 5.89414321,
       5.22208835, 4.83943219, 4.47851429, 4.40147046, 4.60468543,
       4.04586731, 5.69428583, 5.72977404, 5.27122396, 4.80015739,
       4.16680459, 5.76825869, 4.89012203, 4.86762996, 4.42321339,
       5.31444083, 4.47877134, 5.9618003 , 5.26751532, 5.56466476,
       5.59485303, 5.93819706, 5.16681365, 6.35119593, 5.35866449,
       4.51909703, 6.02470454, 5.15188816, 5.20094047, 6.45667

In [31]:
# means list for xVelocity
means_list

array([-6.97185392e-01, -3.88343565e-02, -4.06233161e-02, -1.47562677e-02,
       -1.47104613e-02,  1.40566223e-03,  1.27531241e-03,  3.68707294e-03,
        1.20821550e-04, -9.37115534e-03, -1.56124221e-02,  1.60726082e-03,
       -2.66152439e-02,  6.82093912e-02,  1.12951421e-02,  3.40711049e-02,
       -1.68068666e-02, -1.06901538e-03, -5.56923348e-02, -3.05265230e-02,
       -3.83155382e-02, -4.65438927e-02, -6.27664191e-03,  7.38421961e-02,
        8.01255244e-02,  1.17499877e-01, -5.55984478e-02,  8.74862419e-02,
       -1.01212109e-01,  2.15005036e-02, -1.81222197e-01,  1.00951418e-01,
       -6.45924774e-02,  1.19115643e-01,  1.25265855e+00,  5.17420767e-01,
        7.53707023e-01,  9.14984760e-01, -1.95507651e-01, -5.09766684e-01,
       -1.29388009e+00,  3.77369910e-02,  8.18564257e-02,  2.16506122e-01,
       -3.53545372e-01, -3.16175002e-02,  4.21018624e-01,  1.13375822e+00,
        1.03947301e+00, -5.49415270e-03,  2.05676122e-02, -1.02352140e+00,
        1.13500568e+00,  

In [32]:
condition = 2 * stds_list + means_list
condition

array([ 8.18979666,  2.08490333,  2.46818102,  1.03552389,  1.14984077,
        0.62916947,  0.95058113,  1.17763047,  1.64383584,  1.57660585,
        1.86134774,  1.77165483,  1.87585402,  2.06758365,  2.21324217,
        2.14956944,  2.17129348,  2.16999152,  2.0964448 ,  2.13077086,
        2.28911853,  2.3949083 ,  2.43140313,  3.18932562,  3.52038002,
        2.93395144,  3.08082692,  3.50223155,  3.37813868,  4.16580692,
        4.2321283 ,  8.09955531,  6.09749378,  9.91426391, 12.37578098,
        9.07540493, 15.47378468, 10.84055524, 11.21312277, 10.81487355,
        9.3347369 , 11.27375722,  9.96642979,  6.24563816, 11.43474105,
       10.41255921, 10.09988301, 10.09078681,  9.84241392,  9.20387671,
        8.11230224, 10.36505027, 12.59455376, 10.8958086 ,  9.41979237,
        8.44785449, 11.38952734,  9.35585401,  9.00901958,  9.35642887,
        9.87862063,  9.09067468, 12.86760343, 10.17104269, 12.07091008,
       12.01920976, 10.93404445, 10.32244812, 13.30324045, 11.45

In [33]:
# var = true_val if condition else false_val

In [34]:
dv11_list = []
for i in range(len(grouped_df)):
    mylist = list(grouped_df.get_group(i)['xVelocity'].apply(lambda x : x if x >= condition[i] else 0))
    dv11_list.append(100 * sum(mylist) / len(mylist))

In [35]:
dv11_list

[31.30632324364723,
 8.20261577084153,
 8.250989216505518,
 1.6553786954122196,
 1.1834684871221246,
 0.766984795688782,
 1.4304022754911185,
 2.2064700512960083,
 3.109069218541197,
 2.5599320964247005,
 3.340949246613707,
 3.3547957955959973,
 3.322578553624032,
 7.595660357547354,
 5.239258390051362,
 6.81899725868056,
 4.062512928955786,
 5.312406335730707,
 2.9503777084048948,
 3.657002036601367,
 4.185514670009619,
 4.483619422162769,
 6.87809422093865,
 14.062875802782987,
 17.416540963322333,
 15.886864631371147,
 9.623679599087815,
 18.04898089447601,
 10.536779847157879,
 19.927835241989776,
 17.613509048723863,
 54.549408509064044,
 24.65369608800207,
 46.08838398344006,
 78.07300182858958,
 53.500879339934016,
 8.30128204524034,
 52.38746658301417,
 41.22182010503737,
 51.91084976452122,
 28.972968725171533,
 35.91109281317452,
 72.21013966110665,
 36.352958035277375,
 52.049612214535394,
 61.45380101180436,
 55.012705610005405,
 69.42109078423294,
 84.87088697776194,
 33.2

# dv 12

In [36]:
df.head()

recordingId  trackId  frame  trackLifetime    xCenter   yCenter    heading  \
0            0        0      0              0  131.38519 -34.78380  261.84968   
1            0        0      1              1  131.33830 -35.13993  261.95002   
2            0        0      2              2  131.28821 -35.50286  262.00456   
3            0        0      3              3  131.23861 -35.86783  262.03306   
4            0        0      4              4  131.18973 -36.23341  262.06697   

     width   length  xVelocity  yVelocity  xAcceleration  yAcceleration  \
0  1.76028  4.03141   -1.20819   -9.06651       -0.01047        0.52307   
1  1.76028  4.03141   -1.20844   -9.06017       -0.01211        0.55970   
2  1.76028  4.03141   -1.20806   -9.05198       -0.01427        0.61071   
3  1.76028  4.03141   -1.20726   -9.04039       -0.01754        0.67524   
4  1.76028  4.03141   -1.20636   -9.02442       -0.02230        0.75172   

   lonVelocity  latVelocity  lonAcceleration  latAcceleration  
0      9.14622     -0.08938         -0.51631          0.08452  
1      9.14012     -0.07223         -0.55249          0.09037  
2      9.13202     -0.06276         -0.60279          0.09908  
3      9.12046     -0.05740         -0.66630          0.11096  
4      9.10455     -0.05069         -0.74145          0.12583

In [37]:
pos_acc = df[df.lonAcceleration > 0]
pos_acc_gp = pos_acc.groupby('trackId')

In [38]:
stds_pos_acc = pos_acc_gp.std()['lonAcceleration']
means_pos_acc = pos_acc_gp.mean()['lonAcceleration']

stds_pos_acc = np.array(stds_pos_acc)
means_pos_acc = np.array(means_pos_acc)

In [39]:
# std list for lonAcceleration
stds_pos_acc

array([0.59866394, 0.42974269, 0.54696549, 0.38787625, 0.38917786,
       0.25282581, 0.42376363, 0.52552459, 0.52698351, 0.33608956,
       0.47426384, 0.60137871, 0.62818741, 0.47405723, 0.53116456,
       0.66187788, 0.44874243, 0.45677402, 0.52647277, 0.53750899,
       0.55448365, 0.55299574, 0.54602033, 0.46427686, 0.53612128,
       0.5155211 , 0.53926541, 0.54097091, 0.52508711, 0.42923683,
       0.51398972, 0.38853416, 0.41776834, 0.45291027, 0.44072525,
       0.45545172, 0.60170667, 0.45977924, 0.37139188, 0.58004424,
       0.4299502 , 0.46819549, 0.45219941, 0.54449666, 0.55517748,
       0.56026569, 0.4984515 , 0.47281514, 0.48391004, 0.47137753,
       0.51038933, 0.3959993 , 0.46144994, 0.42095295, 0.54034594,
       0.46571804, 0.66291636, 0.45983056, 0.50896113, 0.4555205 ,
       0.40200228, 0.44407111, 0.51405635, 0.34298334, 0.55590793,
       0.47976156, 0.46916078, 0.57069158, 0.41275252, 0.39688967,
       0.42978425, 0.40781392, 0.48185616, 0.50501589, 0.47062

In [40]:
# means list for lonAcceleration
means_pos_acc

array([0.53153903, 0.18618535, 0.40505267, 0.23177987, 0.24243408,
       0.15895757, 0.26131919, 0.43417651, 0.56492394, 0.2196284 ,
       0.32233963, 0.38843183, 0.53743059, 0.27627541, 0.35874259,
       0.61465131, 0.29325781, 0.39226706, 0.44072524, 0.48328776,
       0.42493145, 0.48180544, 0.49649158, 0.29566947, 0.4720092 ,
       0.45078057, 0.4059252 , 0.47325366, 0.55085656, 0.35894647,
       0.52571384, 0.24582627, 0.34694733, 0.30742219, 0.33207992,
       0.32919246, 0.53771647, 0.33618155, 0.28452804, 0.48039101,
       0.31987763, 0.38170215, 0.30888043, 0.39181442, 0.43796043,
       0.41629447, 0.37702733, 0.38794514, 0.28895321, 0.34536944,
       0.36788245, 0.36760971, 0.3697479 , 0.33931486, 0.46432991,
       0.40722251, 0.55983239, 0.35495939, 0.40128717, 0.30361409,
       0.26930591, 0.34112117, 0.3794668 , 0.2374758 , 0.4352973 ,
       0.34595125, 0.40563818, 0.48622461, 0.30449675, 0.28964465,
       0.29214672, 0.30234094, 0.32925221, 0.45957784, 0.33583

In [41]:
condition2 = 2 * stds_pos_acc + means_pos_acc
condition2

array([1.72886691, 1.04567073, 1.49898365, 1.00753236, 1.0207898 ,
       0.66460919, 1.10884645, 1.48522568, 1.61889095, 0.89180753,
       1.27086732, 1.59118926, 1.79380542, 1.22438987, 1.42107171,
       1.93840707, 1.19074267, 1.30581511, 1.49367078, 1.55830574,
       1.53389875, 1.58779693, 1.58853223, 1.22422319, 1.54425176,
       1.48182278, 1.48445603, 1.55519547, 1.60103079, 1.21742013,
       1.55369329, 1.0228946 , 1.18248401, 1.21324272, 1.21353043,
       1.24009591, 1.74112981, 1.25574004, 1.02731181, 1.64047949,
       1.17977803, 1.31809313, 1.21327925, 1.48080774, 1.54831538,
       1.53682585, 1.37393032, 1.33357541, 1.25677329, 1.28812449,
       1.38866112, 1.15960831, 1.29264777, 1.18122076, 1.54502178,
       1.33865859, 1.88566512, 1.2746205 , 1.41920944, 1.21465509,
       1.07331047, 1.22926338, 1.4075795 , 0.92344249, 1.54711315,
       1.30547437, 1.34395974, 1.62760777, 1.13000179, 1.08342399,
       1.15171523, 1.11796878, 1.29296453, 1.46960962, 1.27708

In [42]:
dv12_list = []
for i in range(len(grouped_df)):
    mylist = list(pos_acc_gp.get_group(i)['lonAcceleration'].apply(lambda x : x if x >= condition2[i] else 0))
    dv12_list.append(100 * sum(mylist) / len(mylist))

In [43]:
dv12_list

[11.833711599241465,
 8.98581103993971,
 11.07946037011173,
 9.11041283292978,
 9.628150260756206,
 4.581174701277298,
 10.603165996908812,
 9.836805098247481,
 9.949412145748987,
 8.48873693858845,
 12.056592192033763,
 14.868241237677983,
 11.684812172088135,
 10.800232593340063,
 11.810145179063364,
 10.433599937047525,
 9.573956447963804,
 8.855232051282053,
 11.423196308724826,
 13.5979537037037,
 11.107985393658705,
 11.849173425572516,
 13.865095765158799,
 13.381058119658128,
 11.242312387791745,
 12.672353181272507,
 13.251896433041296,
 9.633130472701906,
 9.607794854734971,
 9.149798698813628,
 8.976724525185789,
 10.082032573289908,
 9.147499738994254,
 11.607222459490021,
 10.675617764030042,
 11.567277514883218,
 11.210844930417498,
 11.868693940168745,
 9.449509230769243,
 11.26066832055331,
 10.481889243580836,
 12.301375486661856,
 10.702625937031494,
 13.153683691492486,
 12.379799859845823,
 12.080208109172021,
 10.413089157185969,
 9.432207584830339,
 12.44667059188

# dv 13

In [44]:
neg_acc = df[df.lonAcceleration < 0]
neg_acc_gp = pos_acc.groupby('trackId')

In [45]:
stds_neg_acc = neg_acc_gp.std()['lonAcceleration']
means_neg_acc = neg_acc_gp.mean()['lonAcceleration']

stds_neg_acc = np.array(stds_neg_acc)
means_neg_acc = np.array(means_neg_acc)

In [46]:
condition3 = 2 * stds_neg_acc + means_neg_acc
condition3

array([1.72886691, 1.04567073, 1.49898365, 1.00753236, 1.0207898 ,
       0.66460919, 1.10884645, 1.48522568, 1.61889095, 0.89180753,
       1.27086732, 1.59118926, 1.79380542, 1.22438987, 1.42107171,
       1.93840707, 1.19074267, 1.30581511, 1.49367078, 1.55830574,
       1.53389875, 1.58779693, 1.58853223, 1.22422319, 1.54425176,
       1.48182278, 1.48445603, 1.55519547, 1.60103079, 1.21742013,
       1.55369329, 1.0228946 , 1.18248401, 1.21324272, 1.21353043,
       1.24009591, 1.74112981, 1.25574004, 1.02731181, 1.64047949,
       1.17977803, 1.31809313, 1.21327925, 1.48080774, 1.54831538,
       1.53682585, 1.37393032, 1.33357541, 1.25677329, 1.28812449,
       1.38866112, 1.15960831, 1.29264777, 1.18122076, 1.54502178,
       1.33865859, 1.88566512, 1.2746205 , 1.41920944, 1.21465509,
       1.07331047, 1.22926338, 1.4075795 , 0.92344249, 1.54711315,
       1.30547437, 1.34395974, 1.62760777, 1.13000179, 1.08342399,
       1.15171523, 1.11796878, 1.29296453, 1.46960962, 1.27708

In [47]:
dv13_list = []
for i in range(len(grouped_df)):
    mylist = list(neg_acc_gp.get_group(i)['lonAcceleration'].apply(lambda x : x if x >= condition3[i] else 0))
    dv13_list.append(100 * sum(mylist) / len(mylist))

In [48]:
dv13_list

[11.833711599241465,
 8.98581103993971,
 11.07946037011173,
 9.11041283292978,
 9.628150260756206,
 4.581174701277298,
 10.603165996908812,
 9.836805098247481,
 9.949412145748987,
 8.48873693858845,
 12.056592192033763,
 14.868241237677983,
 11.684812172088135,
 10.800232593340063,
 11.810145179063364,
 10.433599937047525,
 9.573956447963804,
 8.855232051282053,
 11.423196308724826,
 13.5979537037037,
 11.107985393658705,
 11.849173425572516,
 13.865095765158799,
 13.381058119658128,
 11.242312387791745,
 12.672353181272507,
 13.251896433041296,
 9.633130472701906,
 9.607794854734971,
 9.149798698813628,
 8.976724525185789,
 10.082032573289908,
 9.147499738994254,
 11.607222459490021,
 10.675617764030042,
 11.567277514883218,
 11.210844930417498,
 11.868693940168745,
 9.449509230769243,
 11.26066832055331,
 10.481889243580836,
 12.301375486661856,
 10.702625937031494,
 13.153683691492486,
 12.379799859845823,
 12.080208109172021,
 10.413089157185969,
 9.432207584830339,
 12.44667059188

In [49]:
mydict = {}
for i in range(13):
    mystr = f"dv{i+1}_list"
    mydict[mystr] = eval(mystr)

In [50]:
mydict

{'dv1_list': [4.443491024010919,
  1.061868845014104,
  1.2544021696945817,
  0.5251400811175494,
  0.5822756144222169,
  0.3138819025835127,
  0.47465291044499797,
  0.5869717005215656,
  0.8218575097547862,
  0.7929885046234186,
  0.9384800831506782,
  0.8850237848572554,
  0.9512346341706182,
  0.9996871280658546,
  1.1009735131263136,
  1.0577491694528114,
  1.0940501717413895,
  1.0855302662447066,
  1.0760685669995618,
  1.0806486899134242,
  1.163717032539098,
  1.2207260964567512,
  1.218839887343275,
  1.5577417121211907,
  1.7201272490307389,
  1.4082257821034692,
  1.568212684402366,
  1.7073726546672514,
  1.7396753943210306,
  2.0721532094335497,
  2.206675250640261,
  3.999301945656178,
  3.0810431262798423,
  4.897574135170127,
  5.561561214432094,
  4.278992082997858,
  7.360038827818605,
  4.962785238056241,
  5.70431520854547,
  5.662320117707638,
  5.314308493945212,
  5.618010112900867,
  4.9422866808349735,
  3.014566021136802,
  5.894143211986866,
  5.222088354224

In [51]:
df_new = pd.DataFrame(mydict)
df_new

dv1_list  dv2_list     dv3_list     dv4_list    dv5_list  dv6_list  \
0    4.443491  0.726822  -637.347121   429.609629 -156.797302  3.032236   
1    1.061869  0.173996 -2734.354164  1254.966761 -206.952385  0.307443   
2    1.254402  0.224236 -3087.887180  1306.837515 -194.067159  0.347651   
3    0.525140  0.066123 -3558.759519  2657.066263 -144.909338  0.067558   
4    0.582276  0.064200 -3958.241705  3480.595130 -168.943678  0.057979   
..        ...       ...          ...          ...         ...       ...   
608  2.413163  0.464852   -71.906171   -89.692149  -74.002693  2.201860   
609  0.261480  0.254379     3.787930   385.567253  -42.348212  0.205980   
610  0.062081  0.185312    -5.096096  -251.035765  -40.041637  0.050716   
611  0.198102  0.148576   -19.207187  3658.169114  -96.803364  0.156533   
612  0.691522  0.681444    10.705425  2533.405096  -60.198428  0.623203   

     dv7_list    dv8_list     dv9_list  dv10_list  dv11_list  dv12_list  \
0    0.488748 -295.851190   126.633094 -89.417078  31.306323  11.833712   
1    0.042803         NaN          NaN -72.441743   8.202616   8.985811   
2    0.059105         NaN          NaN -73.744091   8.250989  11.079460   
3    0.008460         NaN          NaN -74.308771   1.655379   9.110413   
4    0.007236         NaN          NaN -84.152848   1.183468   9.628150   
..        ...         ...          ...        ...        ...        ...   
608  0.399432  -78.429872   -68.165983 -54.300966   0.000000   0.000000   
609  0.204638    2.500807 -1794.315673 -22.645935  41.872551   1.058951   
610  0.167335   -3.605130  -263.870423 -26.876902  -6.822582   0.000000   
611  0.110336  -11.317623   163.851431 -87.246708   0.000000   1.521754   
612  0.570011   10.781054  2065.045889 -52.105732   0.000000   0.000000   

     dv13_list  
0    11.833712  
1     8.985811  
2    11.079460  
3     9.110413  
4     9.628150  
..         ...  
608   0.000000  
609   1.058951  
610   0.000000  
611   1.521754  
612   0.000000  

[613 rows x 13 columns]

In [52]:
df_new.to_csv("ai_project.csv")