In [1]:
import pandas as pd
import glob
import numpy as np

In [2]:
import pandas as pd
import glob
path = r'data' # use your path
all_files = glob.glob(path + "/*_tracks.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True)

In [3]:
frame

recordingId  trackId  frame  trackLifetime    xCenter   yCenter  \
0                   0        0      0              0  131.38519 -34.78380   
1                   0        0      1              1  131.33830 -35.13993   
2                   0        0      2              2  131.28821 -35.50286   
3                   0        0      3              3  131.23861 -35.86783   
4                   0        0      4              4  131.18973 -36.23341   
...               ...      ...    ...            ...        ...       ...   
14175179           32      466  25286            216   18.27403  -5.41860   
14175180           32      466  25287            217   17.87039  -5.12769   
14175181           32      466  25288            218   17.46547  -4.83655   
14175182           32      466  25289            219   17.05943  -4.54523   
14175183           32      466  25290            220   16.65228  -4.25391   

            heading    width   length  xVelocity  yVelocity  xAcceleration  \
0         261.84968  1.76028  4.03141   -1.20819   -9.06651       -0.01047   
1         261.95002  1.76028  4.03141   -1.20844   -9.06017       -0.01211   
2         262.00456  1.76028  4.03141   -1.20806   -9.05198       -0.01427   
3         262.03306  1.76028  4.03141   -1.20726   -9.04039       -0.01754   
4         262.06697  1.76028  4.03141   -1.20636   -9.02442       -0.02230   
...             ...      ...      ...        ...        ...            ...   
14175179  143.47428  0.00000  0.00000  -10.06592    7.24792       -0.80318   
14175180  143.50798  0.00000  0.00000  -10.09826    7.25714       -0.80333   
14175181  143.54158  0.00000  0.00000  -10.13047    7.26611       -0.80336   
14175182  143.57504  0.00000  0.00000  -10.16261    7.27488       -0.80336   
14175183  143.60837  0.00000  0.00000  -10.19474    7.28360       -0.80336   

          yAcceleration  lonVelocity  latVelocity  lonAcceleration  \
0               0.52307      9.14622     -0.08938         -0.51631   
1               0.55970      9.14012     -0.07223         -0.55249   
2               0.61071      9.13202     -0.06276         -0.60279   
3               0.67524      9.12046     -0.05740         -0.66630   
4               0.75172      9.10455     -0.05069         -0.74145   
...                 ...          ...          ...              ...   
14175179        0.21726     12.40272     -0.16672          0.77473   
14175180        0.21772     12.43430     -0.17124          0.77531   
14175181        0.21787     12.46563     -0.17588          0.77560   
14175182        0.21789     12.49679     -0.18062          0.77579   
14175183        0.21789     12.52793     -0.18540          0.77596   

          latAcceleration  
0                 0.08452  
1                 0.09037  
2                 0.09908  
3                 0.11096  
4                 0.12583  
...                   ...  
14175179         -0.30346  
14175180         -0.30271  
14175181         -0.30216  
14175182         -0.30169  
14175183         -0.30123  

[14175184 rows x 17 columns]

In [6]:
df = frame
df

recordingId  trackId  frame  trackLifetime    xCenter   yCenter  \
0                   0        0      0              0  131.38519 -34.78380   
1                   0        0      1              1  131.33830 -35.13993   
2                   0        0      2              2  131.28821 -35.50286   
3                   0        0      3              3  131.23861 -35.86783   
4                   0        0      4              4  131.18973 -36.23341   
...               ...      ...    ...            ...        ...       ...   
14175179           32      466  25286            216   18.27403  -5.41860   
14175180           32      466  25287            217   17.87039  -5.12769   
14175181           32      466  25288            218   17.46547  -4.83655   
14175182           32      466  25289            219   17.05943  -4.54523   
14175183           32      466  25290            220   16.65228  -4.25391   

            heading    width   length  xVelocity  yVelocity  xAcceleration  \
0         261.84968  1.76028  4.03141   -1.20819   -9.06651       -0.01047   
1         261.95002  1.76028  4.03141   -1.20844   -9.06017       -0.01211   
2         262.00456  1.76028  4.03141   -1.20806   -9.05198       -0.01427   
3         262.03306  1.76028  4.03141   -1.20726   -9.04039       -0.01754   
4         262.06697  1.76028  4.03141   -1.20636   -9.02442       -0.02230   
...             ...      ...      ...        ...        ...            ...   
14175179  143.47428  0.00000  0.00000  -10.06592    7.24792       -0.80318   
14175180  143.50798  0.00000  0.00000  -10.09826    7.25714       -0.80333   
14175181  143.54158  0.00000  0.00000  -10.13047    7.26611       -0.80336   
14175182  143.57504  0.00000  0.00000  -10.16261    7.27488       -0.80336   
14175183  143.60837  0.00000  0.00000  -10.19474    7.28360       -0.80336   

          yAcceleration  lonVelocity  latVelocity  lonAcceleration  \
0               0.52307      9.14622     -0.08938         -0.51631   
1               0.55970      9.14012     -0.07223         -0.55249   
2               0.61071      9.13202     -0.06276         -0.60279   
3               0.67524      9.12046     -0.05740         -0.66630   
4               0.75172      9.10455     -0.05069         -0.74145   
...                 ...          ...          ...              ...   
14175179        0.21726     12.40272     -0.16672          0.77473   
14175180        0.21772     12.43430     -0.17124          0.77531   
14175181        0.21787     12.46563     -0.17588          0.77560   
14175182        0.21789     12.49679     -0.18062          0.77579   
14175183        0.21789     12.52793     -0.18540          0.77596   

          latAcceleration  
0                 0.08452  
1                 0.09037  
2                 0.09908  
3                 0.11096  
4                 0.12583  
...                   ...  
14175179         -0.30346  
14175180         -0.30271  
14175181         -0.30216  
14175182         -0.30169  
14175183         -0.30123  

[14175184 rows x 17 columns]

#### Number of unique trackID

In [7]:
len(df['trackId'].value_counts())

613

In [8]:
np.min(df['trackId']), np.max(df['trackId'])

(0, 612)

In [9]:
grouped_df = df.groupby('trackId')

# dv 1

In [10]:
dv1_list = list(grouped_df.std()['xVelocity'])
dv1_list

[4.443491024010919,
 1.061868845014104,
 1.2544021696945817,
 0.5251400811175494,
 0.5822756144222169,
 0.3138819025835127,
 0.47465291044499797,
 0.5869717005215656,
 0.8218575097547862,
 0.7929885046234186,
 0.9384800831506782,
 0.8850237848572554,
 0.9512346341706182,
 0.9996871280658546,
 1.1009735131263136,
 1.0577491694528114,
 1.0940501717413895,
 1.0855302662447066,
 1.0760685669995618,
 1.0806486899134242,
 1.163717032539098,
 1.2207260964567512,
 1.218839887343275,
 1.5577417121211907,
 1.7201272490307389,
 1.4082257821034692,
 1.568212684402366,
 1.7073726546672514,
 1.7396753943210306,
 2.0721532094335497,
 2.206675250640261,
 3.999301945656178,
 3.0810431262798423,
 4.897574135170127,
 5.561561214432094,
 4.278992082997858,
 7.360038827818605,
 4.962785238056241,
 5.70431520854547,
 5.662320117707638,
 5.314308493945212,
 5.618010112900867,
 4.9422866808349735,
 3.014566021136802,
 5.894143211986866,
 5.222088354224373,
 4.839432193069827,
 4.478514290498669,
 4.4014704578

# dv 2

In [11]:
dv2_list = list(grouped_df.std()['lonAcceleration'])
dv2_list

[0.72682239947147,
 0.17399623402982298,
 0.22423590760892848,
 0.06612281845089862,
 0.0641997338111234,
 0.022004020712252232,
 0.05090634525984801,
 0.07943409548634574,
 0.06720779499290207,
 0.05413558004216297,
 0.0782701045990428,
 0.10060726160256549,
 0.14860801817513186,
 0.10673451666129989,
 0.09906670139438975,
 0.13415953089016155,
 0.07433075420735905,
 0.08395590654135726,
 0.11186962205767609,
 0.09465064204268783,
 0.14223591584054732,
 0.13539029827051982,
 0.12243668854851275,
 0.1604030473716144,
 0.1679464780907062,
 0.15023834469299635,
 0.20357379672248774,
 0.2041958096946655,
 0.18786085095810068,
 0.16616189150771746,
 0.30661211463411253,
 0.39687654261017086,
 0.29052175372101396,
 0.5045383095536886,
 0.5538794655731372,
 0.5480920354935632,
 0.7736891679137263,
 0.601660841746243,
 0.49577826373712897,
 0.7411535602052741,
 0.5955768451634483,
 0.6558784481018295,
 0.5357680872184317,
 0.3727960482308189,
 0.7292646193090714,
 0.704553474999911,
 0.653984

# dv 3

In [12]:
stds_list = np.array(dv1_list)
means_list = np.array(grouped_df.mean()['xVelocity'])

In [13]:
dv3_list = (100 * stds_list) / means_list
dv3_list

array([-6.37347121e+02, -2.73435416e+03, -3.08788718e+03, -3.55875952e+03,
       -3.95824171e+03,  2.23298241e+04,  3.72185596e+04,  1.59197203e+04,
        6.80224270e+05, -8.46201430e+03, -6.01111140e+03,  5.50641051e+04,
       -3.57402186e+03,  1.46561509e+03,  9.74731881e+03,  3.10453439e+03,
       -6.50954277e+03, -1.01544869e+05, -1.93216637e+03, -3.54003202e+03,
       -3.03719349e+03, -2.62274173e+03, -1.94186621e+04,  2.10955496e+03,
        2.14679063e+03,  1.19849129e+03, -2.82060516e+03,  1.95158989e+03,
       -1.71884117e+03,  9.63769615e+03, -1.21766279e+03,  3.96161045e+03,
       -4.76997206e+03,  4.11161288e+03,  4.43980622e+02,  8.26984991e+02,
        9.76511908e+02,  5.42389934e+02, -2.91769410e+03, -1.11076700e+03,
       -4.10726506e+02,  1.48872763e+04,  6.03775041e+03,  1.39236988e+03,
       -1.66715326e+03, -1.65164492e+04,  1.14945798e+03,  3.95014933e+02,
        4.23432878e+02, -8.38106562e+04,  1.96710599e+04, -5.56342628e+02,
        5.04823381e+02,  

# dv4

In [14]:
stds_list2 = np.array(dv2_list)
means_list2 = np.array(grouped_df.mean()['lonAcceleration'])

In [15]:
dv4_list = (100 * stds_list2) / means_list2
dv4_list

array([ 4.29609629e+02,  1.25496676e+03,  1.30683751e+03,  2.65706626e+03,
        3.48059513e+03,  1.25315663e+04,  1.08627322e+04,  5.30811522e+03,
        3.50118565e+03,  2.38016714e+04,  1.06672453e+04, -7.35078748e+04,
       -2.82665990e+04, -6.23322432e+03,  1.15030739e+04,  1.89958312e+04,
        1.23177605e+04,  3.05264987e+04,  4.35078671e+03,  2.76950195e+03,
        5.60879345e+03,  8.28874256e+03,  3.53465036e+03,  1.10941752e+04,
        7.98228956e+03,  2.02129104e+04,  1.26463466e+04,  5.35963646e+03,
        5.39147672e+03,  6.77648107e+03,  4.77553938e+03,  8.24327809e+03,
        4.67021497e+03,  1.07775927e+03,  1.61602557e+03, -1.64872505e+04,
        1.33977313e+03,  7.32505700e+03,  3.28102146e+03,  1.29589031e+03,
        7.14880205e+03,  2.70250551e+03,  1.57154311e+03,  2.69939414e+03,
        3.19155105e+03,  1.93155195e+03,  4.05461444e+03,  9.68093532e+03,
        8.91341830e+03,  1.86773423e+03,  3.04417709e+03, -5.84353420e+04,
        1.53750682e+03,  

# dv 5

In [16]:
grouped_by_deacc = df[df['lonAcceleration'] < 0].groupby('trackId')

In [17]:
stds_deacc = np.array(grouped_by_deacc.std()['lonAcceleration'])

In [18]:
means_deacc = np.array(grouped_by_deacc.mean()['lonAcceleration'])

In [19]:
dv5_list = (100 * stds_deacc) / means_deacc
dv5_list

array([-156.79730179, -206.95238545, -194.06715922, -144.90933845,
       -168.94367821, -100.15980161, -203.44571799, -167.21874685,
       -116.90436355, -180.22891969, -155.88852938, -152.23247677,
       -146.48044209, -167.20606707, -223.35434508, -113.37282486,
       -160.21426809, -131.40108432, -140.10129103, -131.91637746,
       -157.69516232, -159.66287543, -140.7794365 , -211.19402053,
       -136.21214154, -120.34890685, -133.44392605, -136.38033895,
        -98.82639208, -125.78068421, -117.17934943, -180.02645269,
       -153.91328229, -173.11664695, -146.43872047, -151.84387507,
       -112.47822898, -155.98950708, -153.20726493, -150.6793795 ,
       -171.37797579, -137.84305382, -161.96499868, -183.45908164,
       -136.06593752, -167.71760549, -147.01421903, -158.7397538 ,
       -181.09216713, -143.87259629, -139.51693932, -127.0803013 ,
       -161.03442446, -146.91483319, -137.05694913, -148.23535992,
       -122.42557288, -149.1611753 , -150.93748255, -166.06164

# DV6

In [23]:
dv6_list = list(grouped_df.mad()['xVelocity'])
dv6_list

[3.032236295266183,
 0.30744293540749906,
 0.3476514109100375,
 0.06755753739250552,
 0.05797852730930609,
 0.015982455729144345,
 0.028859873053026352,
 0.046032033162515806,
 0.06285851564231161,
 0.07572432291971117,
 0.1020393780394708,
 0.08224689045222135,
 0.13105418382572234,
 0.17556989513244933,
 0.12029070725725761,
 0.142600394913407,
 0.12630362232324058,
 0.11448685998974896,
 0.17517044427397482,
 0.13848005005394295,
 0.1809017385982063,
 0.19045117213431603,
 0.16590317826857717,
 0.3353502438913762,
 0.38094983801676535,
 0.34000009948297105,
 0.354953479203653,
 0.41217005762468,
 0.42077806238333937,
 0.48183895734764254,
 0.7665297745827301,
 1.9244342066343885,
 1.1944854610296907,
 2.7966663075680107,
 4.133201627640818,
 2.7696760605276265,
 6.335185547538526,
 3.2121955297702858,
 3.816284864090767,
 3.7970129842610083,
 3.7090457318224606,
 3.930387562089947,
 3.0661806803753335,
 1.2115581800673683,
 3.8905063853942212,
 3.4152867893972885,
 2.964663991782293

# DV 7

In [24]:
dv7_list = list(grouped_df.mad()['lonAcceleration'])
dv7_list

[0.4887482044514624,
 0.04280316186305459,
 0.059105441543131354,
 0.008460284011981319,
 0.007235642505906037,
 0.001351602444816151,
 0.0030678784479794357,
 0.0072716082341417665,
 0.006289053986453718,
 0.003890031766611732,
 0.007005083977209582,
 0.008135872078887853,
 0.014303044092708961,
 0.010911750100236999,
 0.007642198997363977,
 0.01274606223212075,
 0.006566527793644958,
 0.007556757297281729,
 0.01407175309992677,
 0.012242908606530989,
 0.018936191689243653,
 0.01569919976081628,
 0.017560655685268454,
 0.023030170710110945,
 0.027479493415012837,
 0.022569418287388423,
 0.036952086950190845,
 0.03882486061936082,
 0.03623812493736936,
 0.0353544289510069,
 0.08584741419077063,
 0.16989601382463676,
 0.09327687639928996,
 0.2769049116307446,
 0.3255017749792736,
 0.28853501148827226,
 0.519628868152333,
 0.33913378578340525,
 0.2859499047619298,
 0.4513853911363369,
 0.3245135048277508,
 0.398974568304203,
 0.29614433486224273,
 0.11994584881022465,
 0.4424790763549594

# DV 8

In [35]:
percentile_25 = []
percentile_75 = []

for i in range(len(grouped_df)):
    percentile_25.append(np.percentile(grouped_df.get_group(i)['xVelocity'], 25))
    percentile_75.append(np.percentile(grouped_df.get_group(i)['xVelocity'], 75))

In [38]:
percentile_25 = np.array(percentile_25)
percentile_25

array([-2.1048150e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -3.7080000e-02,
        0.0000000e+00, -1.0003450e+00, -1.4274125e+00, -1.1007350e+00,
       -5.5368400e+00, -9.7908500e-01, -1.3239100e+00, -1.5743425e+00,
       -3.5814300e+00, -2.5627800e+00, -1.6073425e+00,  0.0000000e+00,
       -1.4892000e+00, -1.2041000e+00, -1.1149600e+00, -6.8631750e-01,
       -1.0610300e+00, -1.0545800e+00, -2.0113000e-01, -4.4074800e+00,
       -7.7368000e-01, -1.1605950e+00, -8.0045000e-01,  0.0000000e+00,
      

In [40]:
percentile_75 = np.array(percentile_75)
percentile_75

array([ 1.0413775e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.6927500e-02,
        0.0000000e+00,  1.3868350e+00,  3.8853900e+00,  1.4182975e+00,
        7.0371200e+00,  2.6321525e+00,  2.8797900e+00,  1.0884575e+00,
        1.1705600e+00,  2.1229600e+00,  1.3452475e+00,  0.0000000e+00,
        1.3734850e+00,  1.3904600e+00,  1.6537200e+00,  1.7909100e+00,
        1.3509500e+00,  1.2571900e+00,  7.9796750e-01,  1.3448200e+00,
        2.7016825e+00,  2.1057600e+00,  1.2845300e+00,  1.0808000e-01,
      

In [41]:
dv8_list = 100 * ((percentile_75 - percentile_25) / (percentile_75 + percentile_25))
dv8_list

<ipython-input-41-ec4b06e0e25c>:1: RuntimeWarning: invalid value encountered in true_divide
  dv8_list = 100 * ((percentile_75 - percentile_25) / (percentile_75 + percentile_25))


array([-2.95851190e+02,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan, -2.67994045e+02,
                   nan,  6.17656343e+02,  2.16145286e+02,  7.93239913e+02,
        8.38107553e+02,  2.18456748e+02,  2.70181505e+02, -5.48030913e+02,
       -1.97106854e+02, -1.06537675e+03, -1.12653427e+03,             nan,
       -2.47391004e+03,  1.39223009e+03,  5.13898582e+02,  2.24266189e+02,
        8.31946744e+02,  1.14099502e+03,  1.67398580e+02, -1.87820391e+02,
        1.80257157e+02,  

# dv 9

In [42]:
percentile_25_dlong = []
percentile_75_dlong = []

for i in range(len(grouped_df)):
    percentile_25_dlong.append(np.percentile(grouped_df.get_group(i)['lonAcceleration'], 25))
    percentile_75_dlong.append(np.percentile(grouped_df.get_group(i)['lonAcceleration'], 75))

In [43]:
percentile_25_dlong = np.array(percentile_25_dlong)
percentile_75_dlong = np.array(percentile_75_dlong)

In [44]:
dv9_list = 100 * ((percentile_75_dlong - percentile_25_dlong) / (percentile_75_dlong + percentile_25_dlong))
dv9_list

<ipython-input-44-de9b934ef2f4>:1: RuntimeWarning: invalid value encountered in true_divide
  dv9_list = 100 * ((percentile_75_dlong - percentile_25_dlong) / (percentile_75_dlong + percentile_25_dlong))


array([ 1.26633094e+02,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,  1.45071507e+03,
                   nan,  4.70540142e+02,  3.50051629e+02,  2.78970653e+03,
        4.23290554e+02,  9.11187036e+02,  5.14344934e+02,  3.03626656e+02,
        4.03221361e+02,  2.80408490e+02,  3.87218809e+02,             nan,
        4.56558953e+02,  4.26996967e+02,  4.03635933e+02,  8.55265700e+02,
        1.98900662e+03,  9.23597233e+02,  6.03313439e+02,  4.10259797e+02,
        4.21181271e+02,  

# dv 10

In [48]:
percentile_25_deacc = []
percentile_75_deacc = []

for i in range(len(grouped_df)):
    percentile_25_deacc.append(np.percentile(grouped_by_deacc.get_group(i)['lonAcceleration'], 25))
    percentile_75_deacc.append(np.percentile(grouped_by_deacc.get_group(i)['lonAcceleration'], 75))

In [49]:
percentile_25_deacc = np.array(percentile_25_deacc)
percentile_75_deacc = np.array(percentile_75_deacc)

In [50]:
dv10_list = 100 * ((percentile_75_deacc - percentile_25_deacc) / (percentile_75_deacc + percentile_25_deacc))
dv10_list

array([-89.41707804, -72.44174265, -73.7440906 , -74.308771  ,
       -84.15284833, -63.59004053, -83.27864583, -79.12777153,
       -78.1066732 , -68.42720148, -74.36479052, -87.83715987,
       -82.88119344, -80.44629875, -71.95192586, -80.64492985,
       -71.9544585 , -75.55018813, -84.54050388, -81.88751392,
       -82.8113029 , -86.576007  , -79.58058522, -67.39132783,
       -81.94475967, -82.41771288, -88.64672634, -78.877513  ,
       -72.20251414, -76.19282173, -82.16009356, -89.01331486,
       -73.96144014, -78.4590439 , -84.89151176, -83.05198201,
       -77.5704598 , -82.43847589, -77.95721831, -85.47795979,
       -79.42222417, -86.57657203, -80.85287516, -83.23925684,
       -82.78103564, -77.06503934, -87.71432831, -81.07058706,
       -82.40291827, -79.02851003, -84.46305075, -82.94230612,
       -79.95534192, -85.42019163, -77.92518794, -79.44293504,
       -84.79392199, -86.42837976, -83.20764087, -80.93755854,
       -73.42471652, -82.81595888, -84.2989418 , -76.60

# dv 11